JuliaPlots/PlotDocs.jl

docs/recipes.md

I added some text to help clarify the things I found confusing. I also added a short section with troubleshooting in the end, since error messages become much harder to interpret when the error occurs in code written in a macro.
Feel free to modify/restructure any way you see fit!

Add clarifications and troubleshooting to recipes

---

docs/index.md

I think StatPlots should be tagged soon, but if that's not the case the documentation should at least have something that works. (I saw there are tags. It is just not registered?)

Need to fix the doc example for now.

---

docs/input_data.md

Adds documentation for how to import PNG and PDF files for plotting with plots.

Add docs for plotting images

---

docs/basics.md

Use [../ in relative URL](https://www.w3.org/TR/WD-html40-970917/htmlweb.html#h-5.1.2)

Fix broken link from basics to examples

---

docs/recipes.md

The previous command works, but the new command works with only RecipesBase.

Update recipes.md for RecipesBase change

---

docs/index.md

I went over the index page and improved flow.
I've found that I really like Plots.jl as a package, but I'd like to help the documentation. 
I haven't worked on someone else's project before, so I hope I'm doing this correctly.

improving wording on index.md

---

docs/tutorial.md

Fix typo in tutorial

---

docs/layouts.md

Closes  https://github.com/JuliaPlots/Plots.jl/issues/601

Fix graph titles example

---

docs/src/tutorial.md

(this is a resubmission of #42; please see that thread for context.)

tutorial: hide output of y array; mention which backend is used

---

docs/src/index.md

Discussed in https://github.com/JuliaPlots/Plots.jl/issues/1273

Updated waves animation example to incorporate camera pan & progress meter

---

docs/src/supported.md

Fixes https://github.com/JuliaPlots/PlotDocs.jl/pull/72#issuecomment-364349466
Also fixed some copy paste errors in the ids and the onLoad. The onLoad javascript just threw an error, so I threw it out. It also throws an error in http://docs.juliaplots.org/latest/attributes/ where I copied the iframe html from.

Fix table width of supported keyword args

---

docs/src/ecosystem.md

The picture created with Plots that i'd like to propose with this PR is [in LazySets docs](https://juliareach.github.io/LazySets.jl/latest/man/reach_zonotopes_hybrid.html#Example-1) :

add a community package using Plots

---

docs/src/ecosystem.md

add a community package using Plots (cont.)

---

docs/src/output.md

List supported formats, default, format per backend.

Extend section about savefig.

---

docs/src/attributes.md

Reverts JuliaPlots/PlotDocs.jl#101

Revert "fix table urls on attributes page"

---

.travis.yml
Project.toml
docs/Project.toml

Reverts JuliaPlots/PlotDocs.jl#113

Revert "update for documenter updates"

---

docs/src/attributes.md

I think these link addresses are wrong. Note that I didn't test these.

Fix 404 errors

---

docs/src/supported.md

Fix 404 errors (2)

---

docs/src/layouts.md

fixed typo in layouts.md

---

docs/src/layouts.md

Small improvement for the documentation.

Add issue #404 to the documentation.

---

docs/src/layouts.md

In the previous commit the code highlighting was not correct, so its should be all fine now.

Fixed code highlighting

---

docs/src/index.md

This makes the example self-contained.

add "using Plots" in Lorenz Attractor example

---

docs/src/colors.md

Maybe there is a better/clearer/more correct way of mentioning this? Anyways, I had a hard time finding this information and I think this might be a fitting place.

Mention using indexes for colors

---

docs/src/tutorial.md

Docs issue JuliaPlots/Plots.jl#2235

Added missing `using`

---

docs/src/recipes.md

fix https://github.com/JuliaPlots/Plots.jl/issues/2418

fix user recipes example

---

docs/src/layouts.md

I found this confusing that it was a array of arrays initially. Size looks a bit different than others on the page--not sure what settings were used? Let me know if you prefer issues instead of pull--I had to link to image in a fork of PlotReferenceImages.jl

Update layouts.md to show label & title

---

docs/src/backends.md

This section should give useful information for integration with LaTeX - documents.
Having the same for the GR backend would be great.

Add LaTeX workflow

---

docs/src/install.md

https://github.com/JuliaPlots/Plots.jl/pull/2625

add tip to suppress warnings

---

docs/src/assets/tables.css

only overwrite minimum of documenter css values for tables

---

docs/src/recipes.md

The extra indentation was causing these bullets to be rendered as code

Fix indentation

---

docs/src/ecosystem.md

Update GraphRecipes description in the ecosystem overview

Update GraphRecipes description in the ecosystem overview

---

docs/src/backends.md

Update "For the impatient" to "At a glance"

---

docs/src/install.md

i modified `install.md` since it seemed wrong.

Modify install docs

---

docs/src/backends.md

Add an example of how to use `extra_kwargs` using GR.

Update docs for JuliaPlots/Plots.jl/pull/3591

---

src/PlotDocs.jl

Fixes https://github.com/JuliaPlots/PlotDocs.jl/issues/235
Fixes https://github.com/JuliaPlots/PlotDocs.jl/issues/228
Advised from https://github.com/JuliaDocs/Documenter.jl/issues/1620.

Fix editurl for auto-generated md pages

---

src/PlotDocs.jl

Completes https://github.com/JuliaPlots/PlotDocs.jl/pull/240

Fix remaining 404s

---

docs/make.jl
src/PlotDocs.jl

Let's see what works and what doesn't.

Initial examples for gaston (gnuplot)

---

docs/src/recipes.md

As per the discussion [here](https://julialang.slack.com/archives/C6E4SU1D3/p1636705335071200?thread_ts=1636698795.069800&cid=C6E4SU1D3).

Add example for multiple series in multiple subplots 

---

docs/src/backends.md
docs/src/install.md
docs/src/tutorial.md

Fixes https://github.com/JuliaPlots/Plots.jl/issues/4026.

Update docs to reflect GR default

---

docs/src/contributing.md

Add note on format

---

docs/src/backends.md

@BeastyBlacksmith, https://github.com/JuliaPlots/Plots.jl/pull/4080#issuecomment-1024085174.

UnicodePlots: document `extra_kwargs`

---

.github/workflows/docs.yml
docs/src/backends.md
src/PlotDocs.jl

- use `JuliaMono`
- use `png` in backend examples
- disable suppressing logging

`UnicodePlots` use a correct font

---

docs/src/backends.md
docs/src/output.md

I think the tables in the docs would be more legible if they were left-aligned.
**Before this PR**
**After this PR**

update tables to left-aligned

---

docs/src/backends.md

Documentation for the new feature from pull request https://github.com/JuliaPlots/Plots.jl/pull/4172 (not merged)

document how to use additional extra_kwargs for plotly

---

docs/src/input_data.md

Depends on: https://github.com/JuliaPlots/Plots.jl/pull/4287

update batman example for removal of StaticArrays and GeometryTypes

---

docs/src/backends.md

Adds docs for [this PR](https://github.com/JuliaPlots/Plots.jl/pull/4444).

Add docs for Plots.jl PR#4444

---

src/PlotDocs.jl

Fix https://github.com/JuliaPlots/PlotDocs.jl/issues/312, introduced by https://github.com/JuliaPlots/Plots.jl/pull/4525.

fix auto-generated attributes

---

docs/src/backends.md

With https://github.com/JuliaPlots/PlotDocs.jl/issues/324 fixed, this should work now

Fix pyplot plot example

---

docs/src/series_types/contour.md
docs/src/series_types/histogram.md

Fix/clarify small formatting issues on `series_type` pages.

Fix formatting

---

.github/workflows/docs.yml
docs/ci_build.sh

Build failures start to appear on `Plots#master`:
https://github.com/JuliaPlots/Plots.jl/actions/runs/3584940224/jobs/6032265718

try `ubuntu-22.04`

---

docs/ci_build.sh
docs/make.jl
docs/src/backends.md

For https://github.com/JuliaPlots/Plots.jl/pull/4566.

add `Preferences` note

---

docs/make.jl
docs/src/backends.md

Following weak deps at https://github.com/JuliaPlots/UnicodePlots.jl/pull/332.

fix unicodeplots
