- docs/output.md
It should be more clear that `gui()` still exists in Juno, but it's not the default behavior. I think it read before that the only way to get the standalone plot window (when in Juno) would be to change the environment variable. I know it's seems redundant with what's above, but I think this will stop all confusion.
> Juno gui()

- docs/backends.md
Note in the docs that Plotly allows for more output formats to help users make the right choice when needing to save vector graphics.
> note the output formats

- docs/attributes.md
Trying the example line 99 leads to "Stroke not defined": corrected to `stroke` which works.
> Correction of Stroke -> stroke line 99

- docs/input_data.md
With the default seriestype (:path), the color vector [:red, :blue]
will never show up - all is painted in red. This is thus potentially
misleading.
> correct example with color vectors

- docs/examples/pgfplots.md
I got an error trying to use latex strings with pgfplots, because the default behaviour does not add the required latex package before compiling. This shows an example of how to include things like `amssymb` etc.
> Show how to use additional latex packages for pgfplots

- docs/examples/pgfplots.md
- docs/examples/plotlyjs.md
- docs/examples/pyplot.md
The layout commands in the examples don't parse. This should be `;`.
> Fix layout commands

- docs/tutorial.md
Github rendered the ordered lists correctly, but I guess mkdocs requires a smaller subset of Markdown:
https://mkdoc.org.archived.website/docs/howto/text-component/
So the website currently doesn't render the ordered lists well. I changed the ordered lists to that form and hopefully that will do better?
> Fix ordered lists

- docs/index.md
Makes it easier to find the important attribute table. See also https://github.com/JuliaPlots/Plots.jl/issues/995
> Insert a link to attributes and move tutorial up

- docs/src/examples/gr.md
- docs/src/examples/inspectdr.md
- docs/src/examples/pgfplots.md
- docs/src/examples/plotlyjs.md
- docs/src/examples/pyplot.md
- docs/src/examples/unicodeplots.md
In some browsers, the lines with a lot of code in the examples actually
get crossed with the table of contents.
Let me know if there are any other formatting bits and pieces that you
would like to change at the same time.
> Only use 90 columns per line in examples

- docs/src/input_data.md
I think one usually has less groups than polygons.
> typo (change "<" to ">")

- docs/src/colors.md
* except => accept
* Note: Currently, the default color for `linecolor` is `:steelblue`.
> Typo fix; default linecolor info

- docs/src/colors.md
While viewing the documentation about colors at:
http://docs.juliaplots.org/latest/colors/
I was having issues with certain function arguments, like` background_color_inside`. On the website, arguments like `background_color_inside` are incorrectly rendered as `backgroundcolorinside` (with color italicized). This happens with several other arguments. I added backslashes to escape the underscores to prevent from italicizing, so that underscores would be properly rendered. I only note issues in the `Foreground/Background` section.
> Render `background_color_xxx` correctly on site

- .gitignore
- .travis.yml
- Project.toml
- REQUIRE
Use a Project.toml, instead of a mix of a `REQUIRE` file + `Pkg.add` commands to define the environment for the doc build. Also, cap Documenter to 0.19 due to [upcoming breaking changes](https://discourse.julialang.org/t/psa-documenter-jl-breaking-changes-version-capping/16431).
I am basically just playing around here a bit, trying to figure out what would be a good pattern to use for repositories like this that are not really packages. Doing it this way, I don't think you can have PlotDocs as a package in an environment, so I am guessing it might break people's workflows?
> Switch to Project.toml, cap Documenter

- .travis.yml
This follows up on #111. It makes sure that the Travis job actually fails when there is an error somewhere in the script.
The heredoc does not work because Julia does not set the return code appropriately when the scripts are passed via stdin (ref: JuliaLang/julia#30039).
> Use -e option instead of heredoc in Travis script

- docs/src/recipes.md
There was some leftover diff of an old merge in the header of `recipes.md`.
Remove it.
Fixes #125
> Fix leftover from previous merge in `recipes.md`

- docs/src/attributes.md
Code sample say xlims, but description say xlim.
> fix xlim to xlims

- docs/src/attributes.md
Example code:
```
using Plots
x = [0:0.1:3*π;]
y = [sin(i) for i in x]
plot(x, y)
plot!(xticks = ([0:π:3*π;], ["0", "\\pi", "2\\pi"]))
yticks!([-1:1:1;], ["min", "zero", "max"])
savefig("pis.png")
```
Output:
> add information about tick labels

- docs/src/index.md
As suggested in a [recent Discourse post](https://discourse.julialang.org/t/plotting-decision-boundary-regions-for-classifier/21397/7). Updated and optimized version.
I chose MP4 over animated GIF since the GIF is around 30 MB large (and perhaps it's interesting for people to see how easy it is to create MP4 videos).
The corresponding [PR in PlotReferenceImages.jl](https://github.com/JuliaPlots/PlotReferenceImages.jl/pull/37) should be merged before this one.
Note: I've tested the embedded video locally with `Documenter` and it worked fine, but couldn't figure out how to test it with MkDocs.
> Add decision boundary example to index page

- docs/src/learning.md
Add a section for reference sheets, with a link to a Plots.jl reference sheet on GitHub. Previously discussed on [this Plots.jl issue](https://github.com/JuliaPlots/Plots.jl/issues/1961).
> Add a reference sheets section

- src/doc_image_constants.jl
Fix wrong image in "Using Plot Recipes" section of the tutorial.
> generate marginalhist image

- docs/mkdocs.yml
- docs/src/ecosystem.md
- docs/src/graphrecipes/attributes.md
- docs/src/graphrecipes/examples.md
- docs/src/graphrecipes/introduction.md
I finally kicked the procrastination monster and did this.
* Slight restructure of the ecosystem bit, GraphRecipes has its own page separate from all of the other ecosystem examples
* PlotRecipes entry in the ecosystem is deleted, which makes sense, since it is now defunct
* Added examples from GraphRecipes readme as well as an explanation of all of the keyword arguments
Part of https://github.com/JuliaPlots/GraphRecipes.jl/issues/59
> Add documentation for GraphRecipes

- docs/src/recipes.md
Currently, using the return keyword in a recipe function body is not supported, see https://github.com/JuliaPlots/RecipesBase.jl/issues/58.
This PR documents this. 
I am not sure, whether the MethodError is the only error which can be generated by the use of return, but this is what I have encountered and the type information is the type of what I try to return. 
Should we add a link to the RecipesBase Issue in the documentation?
> Document, to not use return keyword in recipes

- docs/src/attributes.md
Here, I added a bit more clarity to the attributes section. Added a concise introduction that includes examples. I changed the formatting just a little bit, because I felt it was confusing and somewhat unclear how to quickly explore documentation from the REPL.
> Added Introduction to Attributes

- docs/src/backends.md
- docs/src/input_data.md
Should be self explaining.
I added a little example to the `pgfplotsx` section showing how to use `extra_kwargs`.
I am not sure whether I should add a note that for now it is only possible to use this mechanism in the original plot command (ie. if `args` is not empty, see https://github.com/JuliaPlots/Plots.jl/issues/2741#issuecomment-635951442).
Also can you tell me how to add the example plot?
Do I simply need to inset this
``` markdown
```@example backends
pgfplotsx(); backendplot() # hide
```
or do I need to define something more?
> add documentation for extra_kwargs in pgfplotsx

- docs/src/output.md
Fix #220 
I also thought about adding a warning about not using SVG when displaying lots of points, as the file size is linear in the size of the input data (I managed to crash Jupyter with a 95MB wireframe plot), but didn't know where to add that (or even if I should).
> Fix #220 (elaborate on default output format)

- docs/src/tutorial.md
the current link in the docs led to the archived GGPlots package. Updated to point to StatsPlots.jl
> update link to StatsPlots.jl

- docs/src/index.md
Coordinates should always be updated after the computation of the derivatives. Else `dy` and `dz` are computed with the values of `l.x` and `l.y` at `t = t + dt`.
> coordinate-update after computing derivatives

- docs/src/install.md
I changed the reference from juliarc to .julia/config/startup.jl. I also added "To do this, add e.g. the following line of code", in case the previous formulation "by setting an enviroment variable" could be less-than-clear for less tech-savy users. I decided however to keep the previous formulation for techincal correctness, opting for a little more verbose but fitting for a wider audience.
A have also added the parenthesis "(if the file does not exist, create it)" because I know that me and others have googled something related to that file not existing, and that this parenthesis is a good way to short-circuit that confusion. A non-trivial amount of the confusion around the startup-file probably stems from exactly this tip, due to the prevalence of Plots.jl.
I have also added "for …
> Removed the outdated reference to juliarc.jl

- docs/src/examples/inspectdr.md
Companion to https://github.com/JuliaPlots/Plots.jl/pull/3628
The `annotations` attribute (and `annotate!` function) has supported
the use of plain tuples containing arguments which are passed to
`text` since v0.22.2.  Document this option for example 20 for the
InspectDR backend (not autogenerated).
Closes (mostly) https://github.com/JuliaPlots/RecipesBase.jl/issues/72
> Document use of tuples in annotations attribute for InspectDR backend

- docs/make.jl
- src/PlotDocs.jl
Should replace [inspectdr.md](https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/src/examples/inspectdr.md) and [unicodeplots.md](https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/src/examples/unicodeplots.md).
Unicodeplots
------
InspectDR
------
> Autogen unicodeplots and inspectdr

- docs/make.jl
- docs/src/backends.md
- docs/src/input_data.md
- docs/src/output.md
- docs/src/tutorial.md
Because of https://github.com/sglyon/PlotlyBase.jl/pull/58, using `plotly()` won't be able to save figures to png anymore.
Fix https://github.com/JuliaPlots/Plots.jl/issues/3703.
> Change plotly() to plotlyjs() (savefig removed from PlotlyBase)

- docs/src/recipes.md
See the method error with RecipesBase 0.9
http://docs.juliaplots.org/latest/recipes/#MethodError:-Cannot-convert-an-object-of-type-Float64-to-an-object-of-type-RecipeData
> Fix docs admonition error about compat of RecipesBase 0.9 in recipes

- docs/src/backends.md
Added `Fine tuning` info under `PyPlot` backend in order to place a colorbar at a more appropriate location for 3D plots.
> Colorbar location for 3D plots under pyplot

- docs/.gitignore
- docs/gallery/config.json
- docs/gallery/index.md
- docs/make.jl
- src/PlotDocs.jl
- src/gallery_config.json
Instead of generating all backend demos in one demo page, this commit
generates one page per backend. This makes exploring the demos easier.
- entry "id" is added to resolve the url-link issue
- notebook generation is disabled
- attributes are generated as hidden page
@BeastyBlacksmith I can't successfully run `include("docs/make.jl")` locally on my macOS but `preview_demos` for GR and pyplot works well.
There are still some issues, e.g., the funny title "Open&#x2F;High&#x2F;Low&#x2F;Close" due to incorrect HTML escaping, but the cross-references are good now.
> generate demo page per backend

- docs/make.jl
Just rechecked the issue https://github.com/JuliaPlots/PlotDocs.jl/pull/256#issuecomment-1065081466 and then I realized that it's due to incorrect asset paths. If using default theme then it's working okay.
For demos generated by `generate_cards(pkgname...)`, the URL redirection will still be broken. But for new demos added by contributors (#277), the URL redirection will work now.
> run DemoCards callbacks

- .github/workflows/docs.yml
- docs/gallery/gaston/index.md
- docs/gallery/gr/index.md
- docs/gallery/inspectdr/index.md
- docs/gallery/pgfplotsx/index.md
- docs/gallery/plotlyjs/index.md
- docs/gallery/pyplot/index.md
- docs/gallery/unicodeplots/config.json
- docs/gallery/unicodeplots/index.md
- docs/make.jl
- src/PlotDocs.jl
Following https://github.com/JuliaPlots/Plots.jl/pull/4149, and https://github.com/JuliaPlots/UnicodePlots.jl/pull/239.
> update gallery for `UnicodePlots`

- docs/src/output.md
`fn` is commonly used as an abbreviation for "function" and it confused at least one user that asked about it.
> Clarify that `fn` is a string representing the filename

- docs/make.jl
- src/PlotDocs.jl
Let's not reinvent the wheel and use `show(io, MIME"text/html"(), df)` which uses the well maintained `PrettyTables.jl` from within `DataFrames.jl`, instead of maintaining our own `html` soup.
> update `to_html` for  generating tables

- docs/make.jl
- src/PlotDocs.jl
Fix https://github.com/JuliaPlots/Plots.jl/issues/4157.
I went for monkey patching `Documenter` as suggested in https://github.com/JuliaPlots/Plots.jl/issues/2337#issuecomment-645048293.
Not the cleanest solution though (but manageable).
If this works, the next step is to fix https://github.com/JuliaPlots/Plots.jl/issues/2337.
> monkey patch `Documenter` to avoid gallery duplicate in search results

- docs/make.jl
Un-needed since release of `DemoCards` 0.5.0.
> remove `DemoCards` monkeypatching

- docs/make.jl
- docs/src/UnitfulExt/unitfulext.md
- docs/src/UnitfulExt/unitfulext_examples.jl
- docs/src/UnitfulExt/unitfulext_plots.jl
- docs/src/input_data.md
I think this change is consistent with the extensions introduced in https://github.com/JuliaPlots/Plots.jl/pull/4649.
The module name is in the end an implementation detail.
Fixes docs build failure following merge of https://github.com/JuliaPlots/Plots.jl/pull/4649.
> rename `UnitfulRecipes` -> `UnitfulExt`

- docs/src/output.md
Add pythonplot to list of backends that can output tex, since it seems that it can indeed output tex using its PGF backend.
> Add pythonplot to tex output

- docs/src/backends.md
I just ran into JuliaPlots/Plots.jl#4887, in which @BeastyBlacksmith points out that `set_default_backend!` was removed.  This PR removes the description of that function.
> Remove outdated description of `set_default_backend!`

- docs/src/UnitfulExt/unitfulext_examples.jl
- docs/src/UnitfulExt/unitfulext_plots.jl
Connected to https://github.com/JuliaPlots/Plots.jl/pull/5098 and https://github.com/JuliaPlots/Plots.jl/pull/5095
> Update unitfulext_examples.jl for new version of Unitful ext
